
<p align="center">
  <img src="https://storage.googleapis.com/kaggle-datasets-images/2243/3791/9384af51de8baa77f6320901f53bd26b/dataset-cover.png" />
  Image source: https://www.kaggle.com/
</p>

## Etapa 1: Instalando o TensorFlow 2.0

In [1]:
!pip uninstall -y tensorflow #Comando necessário, pois o TensorFlow-gpu não desinstala a versão mais recente do Tensorflow, pode gerar conflitos.

Uninstalling tensorflow-2.3.0:
  Successfully uninstalled tensorflow-2.3.0


In [2]:
!pip install tensorflow-gpu==2.0.0.alpha

     |████████████████████████████████| 332.1MB 50kB/s 
     |████████████████████████████████| 51kB 7.1MB/s 
     |████████████████████████████████| 3.0MB 49.5MB/s 
     |████████████████████████████████| 419kB 43.0MB/s 


## Etapa 2: Importando as bibliotecas e a base de dados

In [4]:
import numpy as np
import datetime
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

In [5]:
tf.__version__

'2.0.0-alpha0'

## Etapa 3: Pré-processamento



### Carregando a base de dados

In [6]:
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [7]:
X_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [8]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [9]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [10]:
y_train[0]

9

0 0 0 0 0 1 0 0 0 0

### Normalizando as imagens

Dividimos cada pixel das imagens das bases de treinamento e teste, utilizando o maior valor que é 255

Com isso, cada pixel estará na faixa entre 0 e 1. Dessa forma, a rede neural vai treinar mais rápida

In [12]:
X_train = X_train / 255.0

In [13]:
X_test = X_test / 255.0

In [14]:
X_train[0]

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000

### Remodelando (reshaping) a base de dados

Como estamos trabalhando com uma rede neural densa, mudamos a dimensão das bases de dados para ficarem no formato de vetor

In [15]:
X_train.shape

(60000, 28, 28)

In [16]:
# Como a dimensão de cada imagem é 28x28, mudamos toda a base de dados para o formato [-1 (todos os elementos), altura * largura]
X_train = X_train.reshape(-1, 28*28)

In [17]:
X_train.shape

(60000, 784)

In [18]:
X_train[0]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [19]:
# Mudamos também a dimensão da base de teste
X_test = X_test.reshape(-1, 28*28)

In [20]:
X_test.shape

(10000, 784)

## Etapa 4: Construindo a Rede Neural Artificial

### Definindo o modelo

Definimos um objeto do tipo Sequential (sequência de camadas)

In [21]:
model = tf.keras.models.Sequential()

In [22]:
model

### Adicionando a primeira camada densa (fully-connected)

Hyper-parâmetros da camada:
- número de units/neurônios: 128
- função de ativação: ReLU
- input_shape (camada de entrada): (784, )

In [24]:
model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784, )))

### Adicionando Dropout

Dropout é uma técnica de regularização na qual alguns neurônios da camada tem seu valor mudado para zero, ou seja, durante o treinamento esses neurônios não serão atualizados. Com isso, temos menos chances de ocorrer overfitting

In [26]:
model.add(tf.keras.layers.Dropout(0.2))

### Adicionando a camada de saída

- units: número de classes (10 na base de dados Fashion MNIST)
- função de ativação: softmax

In [27]:
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

### Compilando o modelo

- Optimizer (otimizador): Adam
- Loss (função de erro): Sparse softmax (categorical) crossentropy 

In [28]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 128)               16512     
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1290      
Total params: 118,282
Trainable params: 118,282
Non-trainable params: 0
_________________________________________________________________


### Treinando o modelo

In [34]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
60000/60000 [==============================] - 6s 99us/sample - loss: 0.4450 - sparse_categorical_accuracy: 0.8417
Epoch 2/10
60000/60000 [==============================] - 6s 99us/sample - loss: 0.4287 - sparse_categorical_accuracy: 0.8461
Epoch 3/10
60000/60000 [==============================] - 6s 98us/sample - loss: 0.4133 - sparse_categorical_accuracy: 0.8525
Epoch 4/10
60000/60000 [==============================] - 6s 99us/sample - loss: 0.4024 - sparse_categorical_accuracy: 0.8551
Epoch 5/10
60000/60000 [==============================] - 6s 99us/sample - loss: 0.3913 - sparse_categorical_accuracy: 0.8612
Epoch 6/10
60000/60000 [==============================] - 6s 100us/sample - loss: 0.3814 - sparse_categorical_accuracy: 0.8636
Epoch 7/10
60000/60000 [==============================] - 6s 100us/sample - loss: 0.3720 - sparse_categorical_accuracy: 0.8666
Epoch 8/10
60000/60000 [==============================] - 6s 99us/sample - loss: 0.3622 - sparse_categorical_accurac

### Avaliação do modelo e previsão

In [35]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

10000/10000 [==============================] - 1s 53us/sample - loss: 56.7869 - sparse_categorical_accuracy: 0.7725


In [36]:
print("Test accuracy: {}".format(test_accuracy))

Test accuracy: 0.7724999785423279


In [37]:
test_loss

56.78685189285278