## TensorFlow 1.X




### Instalando o TensorFlow 1.X



In [1]:
!pip uninstall -y tensorflow #Comando necessário, pois o TensorFlow-gpu não desinstala a versão mais recente do Tensorflow, pode gerar conflitos.

Uninstalling tensorflow-2.3.0:
  Successfully uninstalled tensorflow-2.3.0


In [2]:
!pip install tensorflow-gpu==1.13.1

     |████████████████████████████████| 345.2MB 47kB/s 
     |████████████████████████████████| 368kB 38.2MB/s 
     |████████████████████████████████| 3.2MB 39.5MB/s 
     |████████████████████████████████| 51kB 6.7MB/s 
  Found existing installation: tensorflow-estimator 2.3.0
    Uninstalling tensorflow-estimator-2.3.0:
      Successfully uninstalled tensorflow-estimator-2.3.0
  Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninstalled tensorboard-2.3.0


In [6]:
import tensorflow as tf

In [7]:
tf.__version__

'1.13.1'

### Constantes

#### Definindo uma constante

In [8]:
# Definindo uma constante no TensorFlow
tensor = tf.constant([[23, 4], 
                      [32, 51]])

In [9]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [10]:
# Se uma sessão não for inicializada, não podemos acessar os valores da constante
tensor.eval()

ValueError: ignored

#### Acessando os valores de uma constante

In [11]:
session = tf.Session()

In [12]:
session.run(tf.global_variables_initializer())

In [13]:
tensor_value = session.run(tensor)

In [14]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

### Variáveis

#### Definindo uma variável

In [15]:
# Definindo uma variável no TensorFlow
variable = tf.Variable([[30, 20], [10, 45]])

Instructions for updating:
Colocations handled automatically by placer.


In [16]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [17]:
# Se uma sessão na for inicializada, não podemos acessar os valores das variáveis
variable.eval()

ValueError: ignored

#### Acessando os valores de uma variável

In [18]:
# Inicializando uma sessão
session = tf.Session()

In [19]:
# Inicializando TODAS as variáveis de uma seção
session.run(tf.global_variables_initializer())

In [20]:
# Executando o método eval no ambiente com a sessão inicializada para conseguir buscar os valores
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

## TensorFlow 2.0

### Instalando o TensorFlow 2.0

In [22]:
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.1MB 53kB/s 
     |████████████████████████████████| 419kB 37.5MB/s 
     |████████████████████████████████| 3.0MB 37.8MB/s 
  Found existing installation: tensorflow-gpu 1.13.1
    Uninstalling tensorflow-gpu-1.13.1:
      Successfully uninstalled tensorflow-gpu-1.13.1


In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.0.0-alpha0'

### Constantes

#### Definindo uma constante

In [6]:
# Definindo uma constante no TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], 
                         [32, 51]])

In [7]:
tensor_20

<tf.Tensor: id=2, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [8]:
# Acessando as dimensões de um tensor
tensor_20.shape

TensorShape([2, 2])

#### Acessando os valores de uma constante

In [9]:
# Acessando os valores de um tensor com o numpy e sem precisar de uma sessão
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [10]:
# Podemos converter um numpy array para um tensor do TensorFlow
numpy_tensor = np.array([[23,  4], [32, 51]])

In [11]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [12]:
tensor_from_numpy

<tf.Tensor: id=5, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variáveis

#### Definindo uma variável

In [13]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Acessando os valores de uma variável

In [14]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Alterando um valor específico de uma variável

In [15]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [16]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operações com tensores

In [17]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=29, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Adição entre um escalar e um tensor

In [18]:
tensor + 2

<tf.Tensor: id=32, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplicação entre um escalar e um tensor

In [19]:
tensor * 5

<tf.Tensor: id=35, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Usando funções do numpy nos tensores do TensorFlow

In [21]:
# Obtendo o quadrado de todos os membros de um tensor
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [22]:
# Obtendo a raiz quadrada de todos os membros de um tensor
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product (produto escalar) entre dois tensores

In [23]:
tensor

<tf.Tensor: id=29, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [24]:
tensor_20

<tf.Tensor: id=2, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [25]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Strings no TensorFlow 2.0

In [26]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=46, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Operações simples com strings

In [28]:
tf.strings.length(tf_string)

<tf.Tensor: id=50, shape=(), dtype=int32, numpy=10>

In [29]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=55, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Armazenando arrays (vetores) de strings

In [30]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [31]:
# Iterating through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
