In [1]:
import tensorflow as tf

In [5]:
tf.compat.v1.disable_eager_execution()
a = tf.constant([[1,2,3],
                 [4,5,6]])
b = tf.constant([[0,0],
                 [1,0],
                 [0,1]])

sess = tf.compat.v1.Session()
result = sess.run(tf.matmul(a,b))
print(result)
sess.close()

[[2 3]
 [5 6]]


In [6]:
x = tf.constant([0,1,0])
print(x)

Tensor("Const_8:0", shape=(3,), dtype=int32)


In [9]:
x = tf.expand_dims(x,1)
sess = tf.compat.v1.Session()
result = sess.run(tf.matmul(a,x))
print(result)
sess.close()

[[2]
 [5]]


In [10]:
print(x.shape)

(3, 1)


In [11]:
transposta = tf.transpose(a)

In [15]:
sess = tf.compat.v1.Session()
result = sess.run(transposta)
print(result)
sess.close()

[[1 4]
 [2 5]
 [3 6]]
