In [1]:
import tensorflow as tf

In [2]:
#Criando variável
var = tf.Variable(10)

In [3]:
print(var)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


In [16]:
matriz = tf.random.normal([3,5], 0, 1, tf.float16)
var2 = tf.Variable(matriz)
tf.print(var2)

[[-0.915527344 -0.295654297 1.2890625 -1.69433594 0.334960938]
 [-0.642578125 0.250732422 -1.21191406 0.126220703 -0.921875]
 [0.0376281738 0.588867188 -0.578613281 -0.217529297 0.466796875]]
