# NumPy

# Algebra Linear - Auto-valores e auto-vetores

* Determinando autovalores e autovetores de matrizes


In [1]:
import numpy as np

In [2]:
X = np.array([[3,0,0],[0,3,2],[0,-1,0]])

In [3]:
autovalores,autovetores = np.linalg.eig(X)

In [4]:
autovalores

array([1., 2., 3.])

In [5]:
autovetores

array([[ 0.        ,  0.        ,  1.        ],
       [ 0.70710678, -0.89442719,  0.        ],
       [-0.70710678,  0.4472136 ,  0.        ]])

* Os autovetores estão normalizados

In [6]:
Y = np.array([[4,-2],[1,1]])

In [7]:
autovalores,autovetores = np.linalg.eig(Y)

In [8]:
autovalores

array([3., 2.])

In [9]:
autovetores

array([[0.89442719, 0.70710678],
       [0.4472136 , 0.70710678]])