# NumPy

# Algebra Linear - Matriz e determiante

* Criando matrizes, calculando matriz inversa, transposta e determinante


In [1]:
import numpy as np

* Criando matriz 3X3

In [2]:
X = np.array([[3,0,0],[0,3,2],[0,-1,0]])
Y = np.array([[1,4,6],[2,6,8],[5,9,1]])

* Criando matriz 2X2

In [3]:
Z = np.array([[4,-2],[1,1]])

* Criando matriz 4X4

In [4]:
W = np.array([[1,7,3,1],[6,3,9,0],[2,7,4,5],[1,9,9,4]])

* Determinante

In [5]:
det_X = np.linalg.det(X)

In [6]:
print(det_X)

6.000000000000001


In [7]:
det_Y = np.linalg.det(Y)

In [8]:
print(det_Y)

13.999999999999996


In [9]:
det_Z = np.linalg.det(Z)

In [10]:
print(det_Z)

6.0


In [11]:
det_W = np.linalg.det(W)

In [12]:
print(det_W)

921.0


* Matriz inversa

In [13]:
inv_X = np.linalg.inv(X)

In [14]:
print(inv_X)

[[ 0.33333333  0.          0.        ]
 [ 0.          0.         -1.        ]
 [ 0.          0.5         1.5       ]]


In [15]:
inv_Y = np.linalg.inv(Y)

In [16]:
print(inv_Y)

[[-4.71428571  3.57142857 -0.28571429]
 [ 2.71428571 -2.07142857  0.28571429]
 [-0.85714286  0.78571429 -0.14285714]]


In [17]:
inv_Z = np.linalg.inv(Z)

In [18]:
print(inv_Z)

[[ 0.16666667  0.33333333]
 [-0.16666667  0.66666667]]


In [19]:
inv_W = np.linalg.inv(W)

In [20]:
print(inv_W)

[[ 0.07166124  0.13572204  0.17589577 -0.23778502]
 [ 0.21824104 -0.02605863 -0.00977199 -0.04234528]
 [-0.12052117  0.02931596 -0.11400651  0.17263844]
 [-0.23778502 -0.0412595   0.23452769  0.01628664]]


* Matriz transposta

In [21]:
transp_X = X.T

In [22]:
print(transp_X)

[[ 3  0  0]
 [ 0  3 -1]
 [ 0  2  0]]


In [23]:
transp_Y = Y.T

In [24]:
print(transp_Y)

[[1 2 5]
 [4 6 9]
 [6 8 1]]


In [25]:
transp_Z = Z.T

In [26]:
print(transp_Z)

[[ 4  1]
 [-2  1]]


In [27]:
transp_W = W.T

In [28]:
print(transp_W)

[[1 6 2 1]
 [7 3 7 9]
 [3 9 4 9]
 [1 0 5 4]]


* Traço da matriz

In [29]:
traco_X = np.trace(X)

In [30]:
print(traco_X)

6


In [31]:
traco_Y = np.trace(Y)

In [32]:
print(traco_Y)

8


In [33]:
traco_Z = np.trace(Z)

In [34]:
print(traco_Z)

5


In [35]:
traco_W = np.trace(W)

In [36]:
print(traco_W)

12
