# NumPy - básico

* Criação e manipulação de arranjos multidimensionais utilizando a biblioteca NumPy do Python


Importanto a biblioteca NumPy

In [1]:
import numpy as np

Criando um arranjo NumPy

In [2]:
tmp1 = [1,2,3,4,5]
tmp2 = [1.2,2.3,3.4,4.5,5.6]

In [3]:
a = np.array(tmp1)
b = np.array(tmp2)

In [4]:
print(tmp1)
print(tmp2)

[1, 2, 3, 4, 5]
[1.2, 2.3, 3.4, 4.5, 5.6]


In [5]:
print(a)

[1 2 3 4 5]


In [6]:
print(b)

[1.2 2.3 3.4 4.5 5.6]


Exibindo o tipo do arranjo

In [7]:
a.dtype

dtype('int64')

In [8]:
b.dtype

dtype('float64')

Criando arranjo manualmente com dtype float64

In [9]:
c = np.array([[1,2,3],[3,4,5]],dtype='float64')

In [10]:
c

array([[1., 2., 3.],
       [3., 4., 5.]])

In [11]:
c.dtype

dtype('float64')

Exibindo formato do arranjo

In [12]:
c.shape

(2, 3)

Determinando a dimensão do arranjo

In [13]:
c.ndim

2

Determinando o número de elementos do arranjo

In [14]:
c.size

6

Determinando o tipo da variável

In [15]:
type(c)

numpy.ndarray

Criando uma matriz 3X4 com todos elementos nulos e do tipo inteiro

In [16]:
np.zeros((3,4),dtype='int64')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Criando uma matriz 4X5 com todos elementos iguais a um e do tipo float

In [17]:
np.ones((4,5),dtype='float64')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Criando uma matriz 3X3 com todos os elementos iguais a 5

In [18]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

Criando uma matriz 3X3 identidade

In [19]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Somando elementos do arranjo com número constante

In [20]:
np.array([1,2,3]) + 2

array([3, 4, 5])

Somando dois arranjos de tamanhos iguais

In [21]:
np.array([1,2,3]) + np.array([1,2,3])

array([2, 4, 6])

In [22]:
a = np.array([1,2,3])
b = np.array([1,2])
c = np.array([3,4,5])

In [23]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [24]:
if(a.shape == b.shape):
    print(a + b)
else:
    print("Impossivel somar")

Impossivel somar


In [25]:
if(a.shape == c.shape):
    print(a + c)
else:
    print("Impossivel somar")

[4 6 8]


Somando arranjos 2D

In [26]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,5,8],[2,1,8]])

In [27]:
a+b

array([[ 4,  7, 11],
       [ 6,  6, 14]])

In [28]:
a-b

array([[-2, -3, -5],
       [ 2,  4, -2]])

In [29]:
a*b

array([[ 3, 10, 24],
       [ 8,  5, 48]])

Adicionando elementos num arranjo

In [30]:
tmp = [1,2,3,4]

In [31]:
tmp.append(5)

In [32]:
tmp

[1, 2, 3, 4, 5]

Removendo elemento do arranjo

In [33]:
np.delete(tmp,4)

array([1, 2, 3, 4])

Produto escalar de dois arranjos

In [34]:
a = [1,2,3]
b = [4,5,6]

c= np.dot(a,b)

In [35]:
c

32

Soma dos elementos do arranjo

In [36]:
a= np.array([[1,2,3],[4,5,6]])

In [37]:
print(np.sum(a))

21


In [38]:
print(np.sum(a,axis=0))

[5 7 9]


In [39]:
print(np.sum(a,axis=1))

[ 6 15]


Transposta de uma matriz

In [40]:
a= np.array([[1,2,3],[4,5,6]])

In [41]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

Utilizando condicionais

In [42]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [43]:
a > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [44]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [45]:
a[(a>5) & (a<9)]

array([6, 7, 8])

In [46]:
a[(a<2) | (a>10)]

array([ 1, 11, 12, 13, 14, 15])

Exibindo indices especificos

In [47]:
a = [1,2,3,4,5,6]

In [48]:
a[2]

3

In [49]:
a[-1]

6

In [50]:
a[0:2]

[1, 2]

In [51]:
a[-3:]

[4, 5, 6]

In [52]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [53]:
b[0]

array([1, 2, 3, 4])

In [54]:
b[:,1]

array([2, 6])

In [55]:
b[1,:]

array([5, 6, 7, 8])

Invertendo valores

In [56]:
b[::-1]

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [57]:
a[::-1]

[6, 5, 4, 3, 2, 1]