# NumPy - intermediário

* Diferentes operações matemática utilizando a biblioteca NumPy do Python


In [1]:
import numpy as np

* Vetor espaçado linearmente

In [2]:
X = np.linspace(0,1,11)
print(X)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [3]:
X = np.linspace(0,1,11,retstep=True)
print(X)

(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]), 0.1)


In [4]:
X = np.linspace(0,1,11,endpoint=False)
print(X)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


* Valor absoluto

In [5]:
X = np.array([-3,-2,-1,0,1,2,3])

In [6]:
Y = np.abs(X)
print(Y)

[3 2 1 0 1 2 3]


* Posição do maior valor

In [7]:
X = [1,4,7,1,0,2]

In [8]:
np.argmax(X)

2

In [9]:
X[np.argmax(X)]

7

* Posição do menor valor

In [10]:
np.argmin(X)

4

In [11]:
X[np.argmin(X)]

0

* Potencias

In [12]:
X = np.array([1,2,3,4,5])

In [13]:
Y = np.power(X,2)

In [14]:
print(Y)

[ 1  4  9 16 25]


In [15]:
power_Z = np.array([1,3,2,4,5])

In [16]:
Z = np.power(X,power_Z)

In [17]:
print(Z)

[   1    8    9  256 3125]


* Arrendondamentos

In [18]:
X = [1.12,1.46,1.51,1.69,1.82,1.999]

Valor mais próximo

In [19]:
Y = np.around(X)

In [20]:
print(Y)

[1. 1. 2. 2. 2. 2.]


Considerando uma casa decimal

In [21]:
Z = np.around(X, decimals=1)

In [22]:
print(Z)

[1.1 1.5 1.5 1.7 1.8 2. ]


Valor inteiro mais próximo

In [23]:
W = np.rint(X)

In [24]:
print(W)

[1. 1. 2. 2. 2. 2.]


Valor inteiro mais próximo de zero

In [25]:
X = [-2.6,-1.2,-0.6,0.2,0.9,1.5,2.9]

In [26]:
A = np.fix(X)

In [27]:
print(A)

[-2. -1. -0.  0.  0.  1.  2.]


Floor

Floor do escalar x é o maior inteiro i de modo que i<=x

In [28]:
B = np.floor(X)

In [29]:
print(B)

[-3. -2. -1.  0.  0.  1.  2.]


Ceil

Ceil do escalar x é o menor inteiro i de modo que i>=x

In [30]:
C = np.ceil(X)

In [31]:
print(C)

[-2. -1. -0.  1.  1.  2.  3.]


Valor truncado

In [32]:
D = np.trunc(X)

In [33]:
print(D)

[-2. -1. -0.  0.  0.  1.  2.]


* Produto

In [34]:
X = [2,5]

In [35]:
# produto = 2*5
print(np.prod(X))

10


In [36]:
X = [[2,4],[3,5]]

In [37]:
#produto = 2*4*3*5
print(np.prod(X))

120


In [38]:
#Produto = 2*4 e 3*5
print(np.prod(X,axis=1))

[ 8 15]


In [39]:
#produto = 2*3 e 4*5
print(np.prod(X,axis=0))

[ 6 20]


In [40]:
#produto = 2*3*2
print(np.prod([3, 2], initial=2))

12


* Soma

In [41]:
X = [1,2,3,4,5,6]

In [42]:
Soma1 = np.sum(X)

In [43]:
# soma = 1+2+3+4+5+6
print(Soma1)

21


In [44]:
X = [[1,2,3],[3,6,3]]

In [45]:
Soma2 = np.sum(X,axis=0)

In [46]:
#soma = 1+3, 2+6, 3+3
print(Soma2)

[4 8 6]


In [47]:
Soma3 = np.sum(X,axis=1)

In [48]:
#soma = 1+2+3, 3+6+3
print(Soma3)

[ 6 12]
